services:
  - type: web
    name: kilimalll
    env: node
    plan: free
    region: frankfurt
    buildCommand: "npm install"
    startCommand: "node server/index.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: BASE_URL
        value: https://kilimalll.onrender.com
