-- Migration 004_import_saved_listings.sql
-- GENERATED by scripts/extract-listings.js from public/listing/*.html — do not edit by hand;
-- re-run the script instead. Idempotent: safe to run more than once (ON CONFLICT / NOT EXISTS).
--
-- Imports 9 products captured in the saved Kilimall listing pages.
-- Product slug is "kl-<original Kilimall listing id>" so a saved page can be mapped to its row.
--
-- PLACEHOLDERS (the saved pages do not contain these):
--   * every variant has stock = 50
--   * every variant price = the product price
--   * seller_name = column default
-- Images use local /images/... files when saved locally, otherwise the original kilimall.com image URL.

-- Categories (top level, then second level); existing rows with the same slug are kept
INSERT INTO categories (name, slug, sort_order) VALUES ('Bags', 'bags', 100) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, sort_order) VALUES ('Phones & Accessories', 'phones-accessories', 101) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, sort_order) VALUES ('Fashion Accessories', 'fashion-accessories', 102) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, sort_order) VALUES ('Computers & Accessories', 'computers-accessories', 103) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, sort_order) VALUES ('Kids & Baby Products', 'kids-baby-products', 104) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, sort_order) VALUES ('Electronics & Appliances', 'electronics-appliances', 105) ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id, sort_order)
  SELECT 'Women''s Bags', 'womens-bags', id, 1 FROM categories WHERE slug = 'bags'
  ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id, sort_order)
  SELECT 'Mobile Accessories', 'mobile-accessories', id, 2 FROM categories WHERE slug = 'phones-accessories'
  ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id, sort_order)
  SELECT 'Accessories', 'accessories', id, 3 FROM categories WHERE slug = 'fashion-accessories'
  ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id, sort_order)
  SELECT 'Computer Accessories & Peripherals', 'computer-accessories-peripherals', id, 4 FROM categories WHERE slug = 'computers-accessories'
  ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id, sort_order)
  SELECT 'Mobile Phones', 'mobile-phones', id, 5 FROM categories WHERE slug = 'phones-accessories'
  ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id, sort_order)
  SELECT 'Baby Care', 'baby-care', id, 6 FROM categories WHERE slug = 'kids-baby-products'
  ON CONFLICT (slug) DO NOTHING;
INSERT INTO categories (name, slug, parent_id, sort_order)
  SELECT 'Heating, Cooling & Air Quality', 'heating-cooling-air-quality', id, 7 FROM categories WHERE slug = 'electronics-appliances'
  ON CONFLICT (slug) DO NOTHING;

-- 10000638062: Local fast delivery Ladies Shoulder Casual Portable Leather PU Tote Bag girl Han
INSERT INTO products (sku, name, slug, description, price, original_price, category_id, main_image_url, rating_score, review_count, is_active)
VALUES ('KM-1000229424', 'Local fast delivery Ladies Shoulder Casual Portable Leather PU Tote Bag girl Handbag for Ladies Tote Bags Crossbody Bags for Women Fashion Female Handle Shoulder Shoulder Bag handbags', 'kl-10000638062', 'After purchasing the package, we immediately arrange shipping from Nairobi warehouse. Approximately 1-5 days delivery, the closer the address to Nairobi, the faster the arrival time', 630, 4000,
  (SELECT id FROM categories WHERE slug = 'womens-bags'),
  'https://img.kilimall.com/c/obs/seller/4017/goods_image/251017045613_102ce1376c41afe6a68081bd0ab0d1f0.png?x-image-process=image/format,webp/resize,w_720', 4.8, 4351, true)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_images (product_id, image_url, sort_order)
SELECT p.id, v.image_url, v.sort_order FROM products p, (VALUES ('https://img.kilimall.com/c/obs/seller/4017/goods_image/251017045613_102ce1376c41afe6a68081bd0ab0d1f0.png?x-image-process=image/format,webp/resize,w_720', 0), ('/images/11ba5bfebfa54980914f8a6ae8281b90.904c8.jpg', 1), ('/images/a9ee356147154998a175b2ec01ae9b11.904c8.jpg', 2), ('/images/2e3a09c254cb4127bc3567409b021fe9.904c8.jpg', 3), ('https://img.kilimall.com/c/obs/seller/4017/goods_image/251017045459_1aebf9441f9267468f88b5593107b76c.png?x-image-process=image/format,webp/resize,w_720', 4), ('/images/251d9c5e6b864868b625722841f3cf6c.904c8.jpg', 5), ('https://img.kilimall.com/c/obs/seller/4017/goods_image/240708140032_fe9af78786468cf29b2d3fd11e6335a5.jpg?x-image-process=image/format,webp/resize,w_720', 6), ('https://img.kilimall.com/c/obs/seller/4017/goods_image/251017045450_de1f88528733a0350da98c36eb0541ec.png?x-image-process=image/format,webp/resize,w_720', 7), ('https://img.kilimall.com/c/obs/seller/4017/goods_image/250119105025_cf2b57ee0dbf6c3f0a98071893687298.jpg?x-image-process=image/format,webp/resize,w_720', 8), ('/images/f03a388ad1394989bb3dd8fcdb27a26e.904c8.jpg', 9)) AS v(image_url, sort_order)
WHERE p.slug = 'kl-10000638062' AND NOT EXISTS (SELECT 1 FROM product_images pi WHERE pi.product_id = p.id);
INSERT INTO product_skus (product_id, sku_code, spec_name, price, stock, image_url)
SELECT p.id, v.sku_code, v.spec_name, 630, 50, v.image_url FROM products p, (VALUES
  ('KM-1000229424-1', 'Color: Brown', '/images/240708140032_fe9af78786468cf29b2d3fd11e6335a5.0edb2.jpg'),
  ('KM-1000229424-2', 'Color: Khaki', '/images/240926032902_9a47ccb72c1274cde0527f58a60b8611.0edb2.jpg'),
  ('KM-1000229424-3', 'Color: Black', '/images/0ea6d54df39d4822b20fceff67a4cf59.904c8.jpg')
) AS v(sku_code, spec_name, image_url)
WHERE p.slug = 'kl-10000638062'
ON CONFLICT (sku_code) DO NOTHING;

-- 10002147217: TWS Earphones Wireless Earphones Bluetooth Earphones Headphones Noise Reduction 
INSERT INTO products (sku, name, slug, description, price, original_price, category_id, main_image_url, rating_score, review_count, is_active)
VALUES ('KM-1001033458', 'TWS Earphones Wireless Earphones Bluetooth Earphones Headphones Noise Reduction Sport Game Sleep Bluetooth Earbuds for all smartphones', 'kl-10002147217', 'TWS Earphones Wireless Earphones Headphones Noise Reduction Sport Game Sleep Bluetooth Earbuds for all smartphones', 459, 2999,
  (SELECT id FROM categories WHERE slug = 'mobile-accessories'),
  'https://img.kilimall.com/c/obs/seller/100004949/goods_image/260312101915_4b4f4e28f30bf8b763eea0af49ed2c20.jpg?x-image-process=image/format,webp/resize,w_720', 4.7, 132, true)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_images (product_id, image_url, sort_order)
SELECT p.id, v.image_url, v.sort_order FROM products p, (VALUES ('https://img.kilimall.com/c/obs/seller/100004949/goods_image/260312101915_4b4f4e28f30bf8b763eea0af49ed2c20.jpg?x-image-process=image/format,webp/resize,w_720', 0), ('https://img.kilimall.com/c/obs/seller/100004949/goods_image/260312101915_f5348ac5aa369f1917baebf5f270a9b9.jpg?x-image-process=image/format,webp/resize,w_720', 1), ('https://img.kilimall.com/c/obs/seller/100004949/goods_image/260312101917_2c3ece7f4a911880928d686117acfcaf.png?x-image-process=image/format,webp/resize,w_720', 2), ('https://img.kilimall.com/c/obs/seller/100004949/goods_image/260312101915_292fee93ef2af95e523a7fbee9bf1ca7.png?x-image-process=image/format,webp/resize,w_720', 3), ('https://img.kilimall.com/c/obs/seller/100004949/goods_image/260312101916_5ff2e29d948eb9e492a3b3538fd669eb.png?x-image-process=image/format,webp/resize,w_720', 4), ('https://img.kilimall.com/c/obs/seller/100004949/goods_image/260312101916_ef4c4bae1263e4d49e87783249263158.png?x-image-process=image/format,webp/resize,w_720', 5), ('https://img.kilimall.com/c/obs/seller/100004949/goods_image/260312101918_5f12cbc94c0236b292c3eb63f5fa246d.png?x-image-process=image/format,webp/resize,w_720', 6), ('https://img.kilimall.com/c/obs/seller/100004949/goods_image/260312101915_0d7b6f672c3674ae79ca0e13a868e25f.jpg?x-image-process=image/format,webp/resize,w_720', 7), ('https://img.kilimall.com/c/obs/seller/100004949/goods_image/260312101915_b93ccf3029c5d8b875d65e093e14574c.jpg?x-image-process=image/format,webp/resize,w_720', 8), ('https://img.kilimall.com/c/obs/seller/100004949/goods_image/260312101915_7278a8593585bfe862eb813372482b16.jpg?x-image-process=image/format,webp/resize,w_720', 9)) AS v(image_url, sort_order)
WHERE p.slug = 'kl-10002147217' AND NOT EXISTS (SELECT 1 FROM product_images pi WHERE pi.product_id = p.id);
INSERT INTO product_skus (product_id, sku_code, spec_name, price, stock, image_url)
SELECT p.id, v.sku_code, v.spec_name, 459, 50, v.image_url FROM products p, (VALUES
  ('KM-1001033458-1', 'Color: White', '/images/260312101915_f5348ac5aa369f1917baebf5f270a9b9.b4006.jpg'),
  ('KM-1001033458-2', 'Color: Black', '/images/260312101915_4b4f4e28f30bf8b763eea0af49ed2c20.b4006.jpg'),
  ('KM-1001033458-3', 'Color: Purple', NULL)
) AS v(sku_code, spec_name, image_url)
WHERE p.slug = 'kl-10002147217'
ON CONFLICT (sku_code) DO NOTHING;

-- 10002473904: ZHJH Blue Light Blocking Glasses Retro Round Anti Blue Light Glasses Anti Eye Fa
INSERT INTO products (sku, name, slug, description, price, original_price, category_id, main_image_url, rating_score, review_count, is_active)
VALUES ('KM-1001135819', 'ZHJH Blue Light Blocking Glasses Retro Round Anti Blue Light Glasses Anti Eye Fatigue Computer Glasses Suitable For Men And Women', 'kl-10002473904', 'Blue light blocking glasses retro round anti blue light glasses anti eye fatigue computer glasses suitable for men and women', 179, 1999,
  (SELECT id FROM categories WHERE slug = 'accessories'),
  'https://img.kilimall.com/c/obs/seller/11375/goods_image/250716002335_7cb8ec192ab67eec3c82ebc60984df53.png?x-image-process=image/format,webp/resize,w_720', 4.8, 3413, true)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_images (product_id, image_url, sort_order)
SELECT p.id, v.image_url, v.sort_order FROM products p, (VALUES ('https://img.kilimall.com/c/obs/seller/11375/goods_image/250716002335_7cb8ec192ab67eec3c82ebc60984df53.png?x-image-process=image/format,webp/resize,w_720', 0), ('/images/52976a6aa7a44c1e9a3e3dc3225c797d.e3f64.png', 1), ('https://img.kilimall.com/c/obs/seller/11375/goods_image/250716002412_3bd088ea5638a60ed34d973ffc9e4294.png?x-image-process=image/format,webp/resize,w_720', 2), ('/images/335ada295162480bb526c2655bdd118a.43350.jpg', 3), ('/images/22afc72b92f140fa9a7b904f5c95ab5a.43350.jpg', 4), ('https://img.kilimall.com/c/obs/seller/11375/goods_image/250310231441_fa1ee2a3362c9688a4bb8f9bc060af6d.jpg?x-image-process=image/format,webp/resize,w_720', 5), ('https://img.kilimall.com/c/obs/seller/11375/goods_image/250310231431_7e69b2e43406ce7aee90d18e37b7fd01.jpg?x-image-process=image/format,webp/resize,w_720', 6), ('https://img.kilimall.com/c/obs/seller/11375/goods_image/250716002340_7a9c8ee58113418690022ba69c546e2b.png?x-image-process=image/format,webp/resize,w_720', 7), ('https://img.kilimall.com/c/obs/seller/11375/goods_image/250716002349_2f614840f9b19f324e753412b0bb9a3b.png?x-image-process=image/format,webp/resize,w_720', 8), ('https://img.kilimall.com/c/obs/seller/11375/goods_image/250310231430_42c382e7c4cbd1bdacd990613ded766e.jpg?x-image-process=image/format,webp/resize,w_720', 9)) AS v(image_url, sort_order)
WHERE p.slug = 'kl-10002473904' AND NOT EXISTS (SELECT 1 FROM product_images pi WHERE pi.product_id = p.id);
INSERT INTO product_skus (product_id, sku_code, spec_name, price, stock, image_url)
SELECT p.id, v.sku_code, v.spec_name, 179, 50, v.image_url FROM products p, (VALUES
  ('KM-1001135819-1', 'Color: Brown', '/images/250716002340_7a9c8ee58113418690022ba69c546e2b.19cbd.png'),
  ('KM-1001135819-2', 'Color: Black', '/images/250716002349_2f614840f9b19f324e753412b0bb9a3b.19cbd.png'),
  ('KM-1001135819-3', 'Color: Olive green', NULL),
  ('KM-1001135819-4', 'Color: Transparent color', '/images/250801072738_52cdeb15d444315009aa63e66e6c146e.19cbd.jpg')
) AS v(sku_code, spec_name, image_url)
WHERE p.slug = 'kl-10002473904'
ON CONFLICT (sku_code) DO NOTHING;

-- 10003240312: Male to Female HDMI to VGA Adapter HD 1080P Audio Cable Converter with 3.5mm Aud
INSERT INTO products (sku, name, slug, description, price, original_price, category_id, main_image_url, rating_score, review_count, is_active)
VALUES ('KM-1001295415', 'Male to Female HDMI to VGA Adapter HD 1080P Audio Cable Converter with 3.5mm Audio Cable for PC Laptop TV Box Computer Monitor Projector', 'kl-10003240312', 'Male to Female HDMI to VGA Adapter HD 1080P Audio Cable Converter with 3.5mm Audio Cable for PC Laptop TV Box Computer Monitor Projector', 289, 1798,
  (SELECT id FROM categories WHERE slug = 'computer-accessories-peripherals'),
  '/images/3403f9346b5f452e91503239c9eb9243.1aba9.jpg', 4.7, 128, true)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_images (product_id, image_url, sort_order)
SELECT p.id, v.image_url, v.sort_order FROM products p, (VALUES ('/images/3403f9346b5f452e91503239c9eb9243.1aba9.jpg', 0), ('https://img.kilimall.com/c/obs/seller/100002118/goods_image/250602134516_6229623c30e6e0f2e055a2f32964ed71.jpg?x-image-process=image/format,webp/resize,w_720', 1), ('https://img.kilimall.com/c/obs/seller/100002118/goods_image/250602134517_2f9ea94102302653b1331c482769263b.jpg?x-image-process=image/format,webp/resize,w_720', 2), ('https://img.kilimall.com/c/obs/seller/100002118/goods_image/250602134518_8225b5324ddc7e8346406c87394b65f8.jpg?x-image-process=image/format,webp/resize,w_720', 3), ('https://img.kilimall.com/c/obs/seller/100002118/goods_image/250602134518_e45d82a75499c79708575d84b99e8284.jpg?x-image-process=image/format,webp/resize,w_720', 4), ('https://img.kilimall.com/c/obs/seller/100002118/goods_image/250602134516_36e1da658312481d39cf0f9e9f1a0c7d.jpg?x-image-process=image/format,webp/resize,w_720', 5), ('https://img.kilimall.com/c/obs/seller/100002118/goods_image/250602134516_b047519250adb824cdf748e06c316a62.jpg?x-image-process=image/format,webp/resize,w_720', 6), ('https://img.kilimall.com/c/obs/seller/100002118/goods_image/250602134516_75a2384859cac4317190af328a55e6f8.jpg?x-image-process=image/format,webp/resize,w_720', 7)) AS v(image_url, sort_order)
WHERE p.slug = 'kl-10003240312' AND NOT EXISTS (SELECT 1 FROM product_images pi WHERE pi.product_id = p.id);
INSERT INTO product_skus (product_id, sku_code, spec_name, price, stock, image_url)
SELECT p.id, v.sku_code, v.spec_name, 289, 50, v.image_url FROM products p, (VALUES
  ('KM-1001295415-1', 'Color: Black', '/images/3403f9346b5f452e91503239c9eb9243.307eb.jpg')
) AS v(sku_code, spec_name, image_url)
WHERE p.slug = 'kl-10003240312'
ON CONFLICT (sku_code) DO NOTHING;

-- 10005455027: [New Arrival]Open Ear Clip Wireless Bluetooth 5.3 Earphones TWS Stereo Earbuds Y
INSERT INTO products (sku, name, slug, description, price, original_price, category_id, main_image_url, rating_score, review_count, is_active)
VALUES ('KM-1001726161', '[New Arrival]Open Ear Clip Wireless Bluetooth 5.3 Earphones TWS Stereo Earbuds YooType K11 HiFi Sound 20H Playtime for iPhone Tecno Android', 'kl-10005455027', '[New Arrival]Open Ear Clip Wireless Bluetooth 5.3 Earphones TWS Stereo Earbuds YooType K11 HiFi Sound 20H Playtime for iPhone Tecno Android', 1099, 5000,
  (SELECT id FROM categories WHERE slug = 'mobile-accessories'),
  '/images/4fcb7703bf15469caf8875a5eb899b0e.96e88.jpg', 5, 2, true)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_images (product_id, image_url, sort_order)
SELECT p.id, v.image_url, v.sort_order FROM products p, (VALUES ('/images/4fcb7703bf15469caf8875a5eb899b0e.96e88.jpg', 0), ('/images/79f03ee924744ebaa72e4d0241123659.b6eb3.jpg', 1), ('/images/40848ba3874e473a845a413c287932e6.b6eb3.jpg', 2), ('/images/7acbb403202a4128b0967feeb41fe4e9.b6eb3.jpg', 3), ('/images/a067c2e6b64b445bb1f4e678c963deee.b6eb3.jpg', 4), ('/images/333e4047e8be4d69b7c113aa19384ecd.b6eb3.jpg', 5), ('/images/f2e1f2e2487c4eacbc5c99d1f79d52de.b6eb3.jpg', 6), ('/images/207e405ea23845bb9d086fa61fc6b1b3.0dee0.png', 7)) AS v(image_url, sort_order)
WHERE p.slug = 'kl-10005455027' AND NOT EXISTS (SELECT 1 FROM product_images pi WHERE pi.product_id = p.id);
INSERT INTO product_skus (product_id, sku_code, spec_name, price, stock, image_url)
SELECT p.id, v.sku_code, v.spec_name, 1099, 50, v.image_url FROM products p, (VALUES
  ('KM-1001726161-1', 'Color: Black', '/images/260116111548_91f3260ff9664e81fe9bc0ae818fd1ea.8dc8b.jpg')
) AS v(sku_code, spec_name, image_url)
WHERE p.slug = 'kl-10005455027'
ON CONFLICT (sku_code) DO NOTHING;

-- 10006105583: TECNO SPARK 50 128GB+4GB 6.78" 120Hz Phone Dynamic Port 50MP Dual Speaker 6700mA
INSERT INTO products (sku, name, slug, description, price, original_price, category_id, main_image_url, rating_score, review_count, is_active)
VALUES ('KM-1001912868', 'TECNO SPARK 50 128GB+4GB 6.78" 120Hz Phone Dynamic Port 50MP Dual Speaker 6700mAh 18W Type-C Dual SIM 4G Side Fingerprint Smart AI Phones', 'kl-10006105583', 'SPARK 50 128GB +8(4+4)GB', 17999, 19999,
  (SELECT id FROM categories WHERE slug = 'mobile-phones'),
  '/images/150bafdc24d24c4c9a37a3bd9980c36a.b4b26.jpg', 4.9, 63, true)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_images (product_id, image_url, sort_order)
SELECT p.id, v.image_url, v.sort_order FROM products p, (VALUES ('/images/150bafdc24d24c4c9a37a3bd9980c36a.b4b26.jpg', 0), ('/images/a86f7c38f8674c26b50cb06171ed80c9.b4b26.jpg', 1), ('/images/c0efa15723194357a6385ca4a6cdd4c3.b4b26.jpg', 2), ('/images/5d6c05472bf64c12ab24229615db8944.b4b26.jpg', 3), ('/images/e710718b5dbf48b28a62e8c3c7cd4e64.b4b26.jpg', 4), ('/images/275e9ad2fd3543d583ad315104aff0db.b4b26.jpg', 5), ('/images/1a7f7a2d19be4389ade096562fe54341.b4b26.jpg', 6)) AS v(image_url, sort_order)
WHERE p.slug = 'kl-10006105583' AND NOT EXISTS (SELECT 1 FROM product_images pi WHERE pi.product_id = p.id);
INSERT INTO product_skus (product_id, sku_code, spec_name, price, stock, image_url)
SELECT p.id, v.sku_code, v.spec_name, 17999, 50, v.image_url FROM products p, (VALUES
  ('KM-1001912868-1', 'Color: Ink Black / Storage: 128GB+8(4+4)GB', '/images/e710718b5dbf48b28a62e8c3c7cd4e64.b4b26.jpg'),
  ('KM-1001912868-2', 'Color: Halo Blue / Storage: 128GB+8(4+4)GB', '/images/275e9ad2fd3543d583ad315104aff0db.b4b26.jpg'),
  ('KM-1001912868-3', 'Color: Titanium Grey / Storage: 128GB+8(4+4)GB', '/images/1a7f7a2d19be4389ade096562fe54341.b4b26.jpg'),
  ('KM-1001912868-4', 'Color: Aurora Purple / Storage: 128GB+8(4+4)GB', '/images/5d6c05472bf64c12ab24229615db8944.b4b26.jpg'),
  ('KM-1001912868-5', 'Color: Bloom Pink / Storage: 128GB+8(4+4)GB', '/images/c0efa15723194357a6385ca4a6cdd4c3.b4b26.jpg')
) AS v(sku_code, spec_name, image_url)
WHERE p.slug = 'kl-10006105583'
ON CONFLICT (sku_code) DO NOTHING;

-- 10006968265: Sanosan Care Oil Ideal for massaging, for pampering your baby’s skin after bathi
INSERT INTO products (sku, name, slug, description, price, original_price, category_id, main_image_url, rating_score, review_count, is_active)
VALUES ('KM-1002088907', 'Sanosan Care Oil Ideal for massaging, for pampering your baby’s skin after bathing 98 % ingredients of natural origin.', 'kl-10006968265', 'Care Oil With sweet-almond oil, organic olive oil and sun-flower oil – ideal for gentle care, With 3 natural oils of the highest quality and natural ingredients', 760, 1170,
  (SELECT id FROM categories WHERE slug = 'baby-care'),
  '/images/b51951d9b170487dab52cca23f3f1ef0.80dbf.png', 5, 1, true)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_images (product_id, image_url, sort_order)
SELECT p.id, v.image_url, v.sort_order FROM products p, (VALUES ('/images/b51951d9b170487dab52cca23f3f1ef0.80dbf.png', 0), ('/images/17e9bc3bd14942c5856e78476e55348d.80dbf.png', 1), ('/images/5e8848b468b74bcf9874504c40a2eabc.2488c.jpg', 2), ('/images/d7951baffb69474b92580683932db0dc.2488c.jpg', 3), ('/images/04db76e3b2804ba9862d525a4b0d22b3.2488c.jpeg', 4), ('/images/6e4fd2659b594470856c8145a5b3895a.2488c.jpeg', 5), ('/images/8b99ac620ec949e5b892175aa186e3bb.2488c.jpeg', 6), ('/images/d1a83eb51466443ca3bd9532741f3749.2488c.jpeg', 7)) AS v(image_url, sort_order)
WHERE p.slug = 'kl-10006968265' AND NOT EXISTS (SELECT 1 FROM product_images pi WHERE pi.product_id = p.id);
INSERT INTO product_skus (product_id, sku_code, spec_name, price, stock, image_url)
SELECT p.id, v.sku_code, v.spec_name, 760, 50, v.image_url FROM products p, (VALUES
  ('KM-1002088907-1', 'Color: Clear', '/images/17e9bc3bd14942c5856e78476e55348d.80dbf.png')
) AS v(sku_code, spec_name, image_url)
WHERE p.slug = 'kl-10006968265'
ON CONFLICT (sku_code) DO NOTHING;

-- 10006993877: EM 1600W 3 in 1 Electric Infrared Heater Quartz Heater with Humidifier, Tube 400
INSERT INTO products (sku, name, slug, description, price, original_price, category_id, main_image_url, rating_score, review_count, is_active)
VALUES ('KM-1002095310', 'EM 1600W 3 in 1 Electric Infrared Heater Quartz Heater with Humidifier, Tube 400w Fan Room Heater, 2 Heat settings, Cool /warm / hot wind for selection. Power indicator light, Adjustable thermostat', 'kl-10006993877', 'EM 1600W 3 in 1 Electric Infrared Heater Quartz Heater with Humidifier, Tube 400w Fan Room Heater, 2 Heat settings, Cool /warm / hot wind for selection. Power', 2699, 4999,
  (SELECT id FROM categories WHERE slug = 'heating-cooling-air-quality'),
  '/images/f0cd0d73dbfd48eab98bb32fbc7f099d.fe5dd.jpg', 1, 1, true)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_images (product_id, image_url, sort_order)
SELECT p.id, v.image_url, v.sort_order FROM products p, (VALUES ('/images/f0cd0d73dbfd48eab98bb32fbc7f099d.fe5dd.jpg', 0), ('/images/13a6f9c4268240bb92adb7e0f37c6027.fe5dd.jpg', 1), ('/images/1b28b9089aa84a0b9d75ef34a6da17ba.fe5dd.jpg', 2), ('/images/b48e65129c0d4b47886e0a98bf06e1cf.fe5dd.jpg', 3), ('/images/5529730d3ac34fde95fc05e836b45792.fe5dd.jpg', 4), ('/images/fe971aaf5e154040b8746d5fb8fe81f5.fe5dd.jpg', 5), ('/images/3c4498cccf5f49e8a3d730a228a9797e.fe5dd.jpg', 6), ('/images/0d0d21f136964fe791992d126d6758f7.fe5dd.jpg', 7), ('/images/afe23000bc6741c7aeaa2cc69814057b.fe5dd.jpg', 8), ('/images/88752a736dac4e56baf26ae814faf866.fe5dd.jpg', 9)) AS v(image_url, sort_order)
WHERE p.slug = 'kl-10006993877' AND NOT EXISTS (SELECT 1 FROM product_images pi WHERE pi.product_id = p.id);
INSERT INTO product_skus (product_id, sku_code, spec_name, price, stock, image_url)
SELECT p.id, v.sku_code, v.spec_name, 2699, 50, v.image_url FROM products p, (VALUES
  ('KM-1002095310-1', 'Color: White', NULL),
  ('KM-1002095310-2', 'Color: QH03', '/images/13a6f9c4268240bb92adb7e0f37c6027.fe5dd.jpg')
) AS v(sku_code, spec_name, image_url)
WHERE p.slug = 'kl-10006993877'
ON CONFLICT (sku_code) DO NOTHING;

-- 18104433: Delicate And Simple Leather Zipper Coin Ladies Mini Short Purse Cute Card Bag
INSERT INTO products (sku, name, slug, description, price, original_price, category_id, main_image_url, rating_score, review_count, is_active)
VALUES ('KM-2477987', 'Delicate And Simple Leather Zipper Coin Ladies Mini Short Purse Cute Card Bag', 'kl-18104433', 'Description Main Material: Patent Leather Closure Type: zipper Interior: Interior Slot Pocket Wallet Length: Short Wallets: Mini Wallets Pattern Type: Solid Dec', 229, 799,
  (SELECT id FROM categories WHERE slug = 'womens-bags'),
  'https://image.kilimall.com/kenya/shop/store/goods/5890/2022/07/16588156972318e571ca21c7b470194ea4c89c5946c20.jpg?x-image-process=image/format,webp/resize,w_720', 4.6, 937, true)
ON CONFLICT (slug) DO NOTHING;
INSERT INTO product_images (product_id, image_url, sort_order)
SELECT p.id, v.image_url, v.sort_order FROM products p, (VALUES ('https://image.kilimall.com/kenya/shop/store/goods/5890/2022/07/16588156972318e571ca21c7b470194ea4c89c5946c20.jpg?x-image-process=image/format,webp/resize,w_720', 0), ('https://image.kilimall.com/kenya/shop/store/goods/5890/2022/07/16588163853717cb51f737502480fa376e19ba1e1ddf3.jpg?x-image-process=image/format,webp/resize,w_720', 1), ('https://image.kilimall.com/kenya/shop/store/goods/5890/2022/07/1658815697451072e038540494b4a8eaac64b65c5aecb.jpg?x-image-process=image/format,webp/resize,w_720', 2), ('https://image.kilimall.com/kenya/shop/store/goods/5890/2022/07/1658815393252c916f37080584429bdcb01494410bae3.jpg?x-image-process=image/format,webp/resize,w_720', 3), ('https://image.kilimall.com/kenya/shop/store/goods/5890/2022/07/1658815698243c446fe05245a4456b654c3e654c9f9be.jpg?x-image-process=image/format,webp/resize,w_720', 4), ('https://image.kilimall.com/kenya/shop/store/goods/5890/2022/07/16588156974511ef60e1c0c3f440e96cdd5f6b0f4c86f.jpg?x-image-process=image/format,webp/resize,w_720', 5), ('https://img.kilimall.com/c/obs/seller/5890/goods_image/250329204003_afc8cfecd5f1894e73db2756eb8776d5.jpg?x-image-process=image/format,webp/resize,w_720', 6)) AS v(image_url, sort_order)
WHERE p.slug = 'kl-18104433' AND NOT EXISTS (SELECT 1 FROM product_images pi WHERE pi.product_id = p.id);
INSERT INTO product_skus (product_id, sku_code, spec_name, price, stock, image_url)
SELECT p.id, v.sku_code, v.spec_name, 229, 50, v.image_url FROM products p, (VALUES
  ('KM-2477987-1', 'Color: Black / Size: one size', '/images/16588163853717cb51f737502480fa376e19ba1e1ddf3.9c654.jpg'),
  ('KM-2477987-2', 'Color: Pink / Size: one size', '/images/16588156972318e571ca21c7b470194ea4c89c5946c20.9c654.jpg')
) AS v(sku_code, spec_name, image_url)
WHERE p.slug = 'kl-18104433'
ON CONFLICT (sku_code) DO NOTHING;
