-- Migration 005_label_imported_sku_specs.sql
-- GENERATED by scripts/extract-listings.js. Relabels variant names imported by the first version of 004
-- ("Black / one size" -> "Color: Black / Size: one size"). Idempotent; a no-op on fresh databases.

UPDATE product_skus SET spec_name = 'Color: Brown' WHERE sku_code = 'KM-1000229424-1' AND spec_name = 'Brown';
UPDATE product_skus SET spec_name = 'Color: Khaki' WHERE sku_code = 'KM-1000229424-2' AND spec_name = 'Khaki';
UPDATE product_skus SET spec_name = 'Color: Black' WHERE sku_code = 'KM-1000229424-3' AND spec_name = 'Black';
UPDATE product_skus SET spec_name = 'Color: White' WHERE sku_code = 'KM-1001033458-1' AND spec_name = 'White';
UPDATE product_skus SET spec_name = 'Color: Black' WHERE sku_code = 'KM-1001033458-2' AND spec_name = 'Black';
UPDATE product_skus SET spec_name = 'Color: Purple' WHERE sku_code = 'KM-1001033458-3' AND spec_name = 'Purple';
UPDATE product_skus SET spec_name = 'Color: Brown' WHERE sku_code = 'KM-1001135819-1' AND spec_name = 'Brown';
UPDATE product_skus SET spec_name = 'Color: Black' WHERE sku_code = 'KM-1001135819-2' AND spec_name = 'Black';
UPDATE product_skus SET spec_name = 'Color: Olive green' WHERE sku_code = 'KM-1001135819-3' AND spec_name = 'Olive green';
UPDATE product_skus SET spec_name = 'Color: Transparent color' WHERE sku_code = 'KM-1001135819-4' AND spec_name = 'Transparent color';
UPDATE product_skus SET spec_name = 'Color: Black' WHERE sku_code = 'KM-1001295415-1' AND spec_name = 'Black';
UPDATE product_skus SET spec_name = 'Color: Black' WHERE sku_code = 'KM-1001726161-1' AND spec_name = 'Black';
UPDATE product_skus SET spec_name = 'Color: Ink Black / Storage: 128GB+8(4+4)GB' WHERE sku_code = 'KM-1001912868-1' AND spec_name = 'Ink Black / 128GB+8(4+4)GB';
UPDATE product_skus SET spec_name = 'Color: Halo Blue / Storage: 128GB+8(4+4)GB' WHERE sku_code = 'KM-1001912868-2' AND spec_name = 'Halo Blue / 128GB+8(4+4)GB';
UPDATE product_skus SET spec_name = 'Color: Titanium Grey / Storage: 128GB+8(4+4)GB' WHERE sku_code = 'KM-1001912868-3' AND spec_name = 'Titanium Grey / 128GB+8(4+4)GB';
UPDATE product_skus SET spec_name = 'Color: Aurora Purple / Storage: 128GB+8(4+4)GB' WHERE sku_code = 'KM-1001912868-4' AND spec_name = 'Aurora Purple / 128GB+8(4+4)GB';
UPDATE product_skus SET spec_name = 'Color: Bloom Pink / Storage: 128GB+8(4+4)GB' WHERE sku_code = 'KM-1001912868-5' AND spec_name = 'Bloom Pink / 128GB+8(4+4)GB';
UPDATE product_skus SET spec_name = 'Color: Clear' WHERE sku_code = 'KM-1002088907-1' AND spec_name = 'Clear';
UPDATE product_skus SET spec_name = 'Color: White' WHERE sku_code = 'KM-1002095310-1' AND spec_name = 'White';
UPDATE product_skus SET spec_name = 'Color: QH03' WHERE sku_code = 'KM-1002095310-2' AND spec_name = 'QH03';
UPDATE product_skus SET spec_name = 'Color: Black / Size: one size' WHERE sku_code = 'KM-2477987-1' AND spec_name = 'Black / one size';
UPDATE product_skus SET spec_name = 'Color: Pink / Size: one size' WHERE sku_code = 'KM-2477987-2' AND spec_name = 'Pink / one size';
